import java.awt.Color;
import java.sql.*;
import Project.ConnectionProvider;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MOJAMMIL
 */
public class newProduct extends javax.swing.JFrame {

    /**
     * Creates new form newProduct
     */
    public newProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pidCon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pNameTxt = new javax.swing.JTextField();
        rateTxt = new javax.swing.JTextField();
        descriptionTxt = new javax.swing.JTextField();
        activateCmb = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New Product ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new buyer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 588, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Product ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 108, -1, -1));

        pidCon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pidCon.setForeground(new java.awt.Color(255, 51, 51));
        pidCon.setText("100");
        getContentPane().add(pidCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 102, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 588, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 177, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Rate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 221, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Description");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 265, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Activate");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 309, -1, -1));

        pNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pNameTxt.setText("Enter Product Name");
        pNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pNameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pNameTxtFocusLost(evt);
            }
        });
        getContentPane().add(pNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 174, 320, -1));

        rateTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rateTxt.setText("Enter Rate");
        rateTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rateTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rateTxtFocusLost(evt);
            }
        });
        getContentPane().add(rateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 218, 320, -1));

        descriptionTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        descriptionTxt.setText("Enter Description");
        descriptionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descriptionTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptionTxtFocusLost(evt);
            }
        });
        getContentPane().add(descriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 262, 320, -1));

        activateCmb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        activateCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No", " " }));
        getContentPane().add(activateCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 306, 320, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 350, 588, 10));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 366, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 366, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close Jframe.png"))); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 366, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/all page background image.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here: 
         try 
                { 
              Connection con=ConnectionProvider.getCon();
                 PreparedStatement pst=con.prepareStatement("select *from product");
                 
                 ResultSet rst=pst.executeQuery();
                 int id=0;
                 while(rst.next())
                 {
                   id=rst.getInt("pid");
                 } 
                   
                
                 id=id+1;
                 pidCon.setText(Integer.toString(id));
                 
   
           
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Error at 317"+e);
        }
    }//GEN-LAST:event_formComponentShown

    private void pNameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNameTxtFocusGained
        // TODO add your handling code here:
         if(pNameTxt.getText().equals("Enter Product Name"))
        {
            pNameTxt.setText("");
            pNameTxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_pNameTxtFocusGained

    private void pNameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pNameTxtFocusLost
        // TODO add your handling code here:
         if(pNameTxt.getText().equals(""))
        {
            pNameTxt.setText("Enter Product Name");
            pNameTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pNameTxtFocusLost

    private void rateTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateTxtFocusGained
        // TODO add your handling code here:
        if(rateTxt.getText().equals("Enter Rate"))
        {
            rateTxt.setText("");
            rateTxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_rateTxtFocusGained

    private void rateTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateTxtFocusLost
        // TODO add your handling code here:
         if(rateTxt.getText().equals(""))
        {
            rateTxt.setText("Enter Rate");
            rateTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_rateTxtFocusLost

    private void descriptionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionTxtFocusGained
        // TODO add your handling code here:
         if(descriptionTxt.getText().equals("Enter Description"))
        {
            descriptionTxt.setText("");
            descriptionTxt.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_descriptionTxtFocusGained

    private void descriptionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionTxtFocusLost
        // TODO add your handling code here:
        if(descriptionTxt.getText().equals(""))
        {
            descriptionTxt.setText("Enter Description");
            descriptionTxt.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_descriptionTxtFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new newProduct().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pName=pNameTxt.getText();
        String rate=rateTxt.getText();
        String description=descriptionTxt.getText();
        String activate=(String)activateCmb.getSelectedItem();
         try 
        { 
             Connection con=ConnectionProvider.getCon();
                 PreparedStatement pst=con.prepareStatement("insert into product(pName,rate,description,activate) values(?,?,?,?)");
                 pst.setString(1, pName);
                 pst.setString(3, description);
                 pst.setString(2, rate);
                 pst.setString(4, activate);
                 
                 int cn=pst.executeUpdate();
                 if(cn==1)
                 {    JOptionPane.showMessageDialog(this,"Insertion Successfully");
                    this.dispose();
                    new newProduct().setVisible(true);
                    
                 
                 }
                 
                 else
                     JOptionPane.showMessageDialog(this,"Insertion Failed");
                      
             
   
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> activateCmb;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField pNameTxt;
    private javax.swing.JLabel pidCon;
    private javax.swing.JTextField rateTxt;
    // End of variables declaration//GEN-END:variables
}
